name: Update BibTeX Nightly

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-bibtex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install PyYAML

    - name: Run BibTeX extraction
      run: |
        cd scripts
        python yaml2bib.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add refs.bib
        git diff --staged --quiet || git commit -m "Update refs.bib [automated]"
        git push
